name: Build PDF
on:
  push:
    branches:
      - main
    paths:
      - 'src/**'

env:
  LEI_VERSION: ${{ contains(github.ref, 'refs/tags/') && github.ref_name || 'dirty' }}
  LEI_PDF: ${{ format('build/LEÍ_v{0}.pdf', contains(github.ref, 'refs/tags/') && github.ref_name || 'dirty') }}

jobs:
  build_pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Pulling repo
        uses: actions/checkout@v6

      - name: Create Build dir
        run: mkdir -p build

      - name: Create pdf
        uses: docker://pandoc/extra:3.8
        with:
          args: >-
            --defaults defaults/latex.yaml
            --metadata version=${{ env.LEI_VERSION }}
            -o ${{ env.LEI_PDF }}

      - name: Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "${{ env.LEI_VERSION }}" "${{ env.LEI_PDF}}" \
          --title "LEÍ ${{ env.LEI_VERSION }}" \
          --notes "TODO: add notes for release"
          gh release verify ${{ env.LEI_VERSION }}
